Repository PHP-CMSIG/search, pull requests merged in 2023-10, with the labels that each got.

#270 Fix code example for SearchCondition
  docs/getting-started/index.rst
Labels: documentation

#271 Add support for PHP Redis Extension ^6.0
  .examples/laravel/composer.lock
  .examples/mezzio/composer.lock
  .examples/spiral/composer.lock
  .examples/symfony/composer.lock
  .examples/yii/composer.lock
  integrations/laravel/composer.lock
  integrations/mezzio/composer.lock
  integrations/spiral/composer.lock
  integrations/symfony/composer.lock
  integrations/yii/composer.lock
  packages/seal-redisearch-adapter/composer.json
  packages/seal-redisearch-adapter/composer.lock
Labels: features, Adapter: RediSearch

#272 Update dependencies
  .examples/laravel/composer.lock
  .examples/mezzio/composer.lock
  .examples/spiral/composer.lock
  .examples/symfony/composer.lock
  .examples/yii/composer.lock
  .github/workflows/callable-test.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/publish-subsplits.yml
  composer.json
  composer.lock
  integrations/laravel/composer.lock
  integrations/mezzio/composer.lock
  integrations/spiral/composer.lock
  integrations/symfony/composer.lock
  integrations/yii/composer.lock
  packages/seal-algolia-adapter/composer.lock
  packages/seal-elasticsearch-adapter/composer.lock
  packages/seal-loupe-adapter/composer.lock
  packages/seal-meilisearch-adapter/composer.lock
  packages/seal-memory-adapter/composer.lock
  packages/seal-multi-adapter/composer.lock
  packages/seal-opensearch-adapter/composer.lock
  packages/seal-read-write-adapter/composer.lock
  packages/seal-redisearch-adapter/composer.lock
  packages/seal-solr-adapter/composer.lock
  packages/seal-typesense-adapter/composer.lock
  packages/seal/composer.lock
  packages/seal/src/Marshaller/Marshaller.php
Labels: DX, dependencies
