Repository PHP-CMSIG/search, pull requests merged in 2024-01, with the labels that each got.

#325 Add void return type for configure methods of commands
  integrations/mezzio/src/Command/IndexCreateCommand.php
  integrations/mezzio/src/Command/IndexDropCommand.php
  integrations/mezzio/src/Command/ReindexCommand.php
  integrations/symfony/src/Command/IndexCreateCommand.php
  integrations/symfony/src/Command/IndexDropCommand.php
  integrations/symfony/src/Command/ReindexCommand.php
  integrations/yii/src/Command/IndexCreateCommand.php
  integrations/yii/src/Command/IndexDropCommand.php
  integrations/yii/src/Command/ReindexCommand.php
Labels: Integration: Symfony, DX, Integration: Mezzio, Integration: Yii

#330 Update Rector to 0.19
  .examples/laravel/composer.json
  .examples/laravel/composer.lock
  .examples/mezzio/composer.json
  .examples/mezzio/composer.lock
  .examples/spiral/composer.json
  .examples/spiral/composer.lock
  .examples/symfony/composer.json
  .examples/symfony/composer.lock
  .examples/symfony/symfony.lock
  .examples/yii/composer.json
  .examples/yii/composer.lock
  .php-cs-fixer.dist.php
  integrations/laravel/composer.json
  integrations/laravel/composer.lock
  integrations/mezzio/composer.json
  integrations/mezzio/composer.lock
  integrations/spiral/composer.json
  integrations/spiral/composer.lock
  integrations/symfony/composer.json
  integrations/symfony/composer.lock
  integrations/yii/composer.json
  integrations/yii/composer.lock
  packages/seal-algolia-adapter/composer.json
  packages/seal-algolia-adapter/composer.lock
  packages/seal-elasticsearch-adapter/composer.json
  packages/seal-elasticsearch-adapter/composer.lock
  packages/seal-loupe-adapter/composer.lock
  packages/seal-meilisearch-adapter/composer.json
  packages/seal-meilisearch-adapter/composer.lock
  packages/seal-memory-adapter/composer.json
  packages/seal-memory-adapter/composer.lock
  packages/seal-multi-adapter/composer.json
  packages/seal-multi-adapter/composer.lock
  packages/seal-opensearch-adapter/composer.json
  packages/seal-opensearch-adapter/composer.lock
  packages/seal-read-write-adapter/composer.json
  packages/seal-read-write-adapter/composer.lock
  packages/seal-redisearch-adapter/composer.json
  packages/seal-redisearch-adapter/composer.lock
  packages/seal-solr-adapter/composer.json
  packages/seal-solr-adapter/composer.lock
  packages/seal-typesense-adapter/composer.json
  packages/seal-typesense-adapter/composer.lock
  packages/seal/composer.json
  packages/seal/composer.lock
Labels: DX

#331 Fix documentation build
  .github/workflows/docs.yml
  docs/requirements.txt
Labels: bug

#322 Allow Symfony 7
  .examples/laravel/.gitignore
  .examples/mezzio/.gitignore
  .examples/spiral/.gitignore
  .examples/symfony/.gitignore
  .examples/symfony/composer.json
  .examples/symfony/composer.lock
  .examples/symfony/config/packages/framework.yaml
  .examples/symfony/phpstan.dist.neon
  .examples/symfony/symfony.lock
  .examples/yii/.gitignore
  .examples/yii/composer.lock
  integrations/symfony/composer.json
  integrations/symfony/composer.lock
Labels: Integration: Symfony, DX, dependencies

#332 Use phpstan.dist.neon instead of phpstan.neon file
  .examples/laravel/.gitignore
  .examples/laravel/phpstan.dist.neon
  .examples/mezzio/.gitignore
  .examples/mezzio/phpstan.dist.neon
  .examples/spiral/.gitignore
  .examples/spiral/composer.lock
  .examples/spiral/phpstan.dist.neon
  .examples/yii/.gitignore
  .examples/yii/phpstan.dist.neon
  integrations/laravel/.gitignore
  integrations/laravel/phpstan.dist.neon
  integrations/mezzio/.gitignore
  integrations/mezzio/phpstan.dist.neon
  integrations/spiral/.gitignore
  integrations/spiral/phpstan.dist.neon
  integrations/symfony/.gitignore
  integrations/symfony/phpstan.dist.neon
  integrations/yii/.gitignore
  integrations/yii/phpstan.dist.neon
  packages/seal-algolia-adapter/.gitignore
  packages/seal-algolia-adapter/phpstan.dist.neon
  packages/seal-elasticsearch-adapter/.gitignore
  packages/seal-elasticsearch-adapter/phpstan.dist.neon
  packages/seal-loupe-adapter/.gitignore
  packages/seal-loupe-adapter/phpstan.dist.neon
  packages/seal-meilisearch-adapter/.gitignore
  packages/seal-meilisearch-adapter/phpstan.dist.neon
  packages/seal-memory-adapter/.gitignore
  packages/seal-memory-adapter/phpstan.dist.neon
  packages/seal-multi-adapter/.gitignore
  packages/seal-multi-adapter/phpstan.dist.neon
  packages/seal-opensearch-adapter/.gitignore
  packages/seal-opensearch-adapter/phpstan.dist.neon
  packages/seal-read-write-adapter/.gitignore
  packages/seal-read-write-adapter/phpstan.dist.neon
  packages/seal-redisearch-adapter/.gitignore
  packages/seal-redisearch-adapter/phpstan.dist.neon
  packages/seal-solr-adapter/.gitignore
  packages/seal-solr-adapter/phpstan.dist.neon
  packages/seal-typesense-adapter/.gitignore
  packages/seal-typesense-adapter/phpstan.dist.neon
  packages/seal/.gitignore
  packages/seal/phpstan.dist.neon
  rector.php
Labels: DX

#323 Add PHP 8.3 to test matrix
  .github/workflows/callable-test.yml
Labels: DX

#333 Allow mezzio with PHP 8.3
  .examples/mezzio/composer.json
  .examples/mezzio/composer.lock
Labels: DX, dependencies

#334 Update elasticsearch, redis and typesense docker image
  .examples/laravel/docker-compose.yml
  .examples/mezzio/docker-compose.yml
  .examples/spiral/docker-compose.yml
  .examples/symfony/docker-compose.yml
  .examples/yii/docker-compose.yml
  docs/getting-started/index.rst
  packages/seal-elasticsearch-adapter/docker-compose.yml
  packages/seal-redisearch-adapter/docker-compose.yml
  packages/seal-typesense-adapter/docker-compose.yml
Labels: Adapter: Elasticsearch, Adapter: Typesense, Adapter: RediSearch, DX

#336 Add Symfony 7 Support for Typesense Adapter and Solr Adapter
  .examples/laravel/composer.lock
  .examples/mezzio/composer.lock
  .examples/spiral/composer.lock
  .examples/symfony/composer.lock
  .examples/yii/composer.lock
  integrations/laravel/composer.lock
  integrations/mezzio/composer.lock
  integrations/spiral/composer.lock
  integrations/symfony/composer.lock
  integrations/yii/composer.lock
  packages/seal-solr-adapter/composer.json
  packages/seal-solr-adapter/composer.lock
  packages/seal-typesense-adapter/composer.json
  packages/seal-typesense-adapter/composer.lock
  packages/seal-typesense-adapter/src/TypesenseAdapterFactory.php
Labels: Adapter: Solr, Adapter: Typesense, DX

#335 Add Support for Loupe 0.5
  .examples/laravel/composer.lock
  .examples/mezzio/composer.lock
  .examples/spiral/composer.lock
  .examples/symfony/composer.lock
  .examples/yii/composer.lock
  integrations/laravel/composer.lock
  integrations/mezzio/composer.lock
  integrations/spiral/composer.lock
  integrations/symfony/composer.lock
  integrations/yii/composer.lock
  packages/seal-loupe-adapter/composer.json
  packages/seal-loupe-adapter/composer.lock
  packages/seal-loupe-adapter/src/LoupeHelper.php
Labels: features, dependencies, Adapter: Loupe

#337 Move from 0.2 to 0.3 branch
  .examples/laravel/composer.json
  .examples/laravel/composer.lock
  .examples/mezzio/composer.json
  .examples/mezzio/composer.lock
  .examples/spiral/composer.json
  .examples/spiral/composer.lock
  .examples/symfony/composer.json
  .examples/symfony/composer.lock
  .examples/yii/composer.json
  .examples/yii/composer.lock
  .github/workflows/callable-test.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  docs/conf.py
  integrations/laravel/composer.json
  integrations/laravel/composer.lock
  integrations/mezzio/composer.json
  integrations/mezzio/composer.lock
  integrations/spiral/composer.json
  integrations/spiral/composer.lock
  integrations/symfony/composer.json
  integrations/symfony/composer.lock
  integrations/yii/composer.json
  integrations/yii/composer.lock
  packages/seal-algolia-adapter/composer.json
  packages/seal-algolia-adapter/composer.lock
  packages/seal-elasticsearch-adapter/composer.json
  packages/seal-elasticsearch-adapter/composer.lock
  packages/seal-loupe-adapter/composer.json
  packages/seal-loupe-adapter/composer.lock
  packages/seal-meilisearch-adapter/composer.json
  packages/seal-meilisearch-adapter/composer.lock
  packages/seal-memory-adapter/composer.json
  packages/seal-memory-adapter/composer.lock
  packages/seal-multi-adapter/composer.json
  packages/seal-multi-adapter/composer.lock
  packages/seal-opensearch-adapter/composer.json
  packages/seal-opensearch-adapter/composer.lock
  packages/seal-read-write-adapter/composer.json
  packages/seal-read-write-adapter/composer.lock
  packages/seal-redisearch-adapter/composer.json
  packages/seal-redisearch-adapter/composer.lock
  packages/seal-solr-adapter/composer.json
  packages/seal-solr-adapter/composer.lock
  packages/seal-typesense-adapter/composer.json
  packages/seal-typesense-adapter/composer.lock
  packages/seal/composer.lock
Labels: dependencies

#338 Add Toflar to Funding.yml of Loupe Adapter
  packages/seal-loupe-adapter/.github/FUNDING.yml
Labels: DX

#339 Upgrade meilisearch docker image to 1.6
  .examples/laravel/docker-compose.yml
  .examples/mezzio/docker-compose.yml
  .examples/spiral/docker-compose.yml
  .examples/symfony/docker-compose.yml
  .examples/yii/docker-compose.yml
  docs/getting-started/index.rst
  packages/seal-meilisearch-adapter/docker-compose.yml
Labels: Adapter: Meilisearch, DX

#344 Fix overview svg image
  docs/_images/overview.svg
Labels: documentation

#345 Upgrade python action to latest version
  .github/workflows/docs.yml
Labels: documentation

#346 Update cache action for publish
  .github/workflows/publish-subsplits.yml
Labels: SEAL Core

#347 Upgrade dependencies and elasticsearch to 8.12
  .examples/laravel/composer.lock
  .examples/laravel/docker-compose.yml
  .examples/mezzio/composer.lock
  .examples/mezzio/docker-compose.yml
  .examples/spiral/composer.lock
  .examples/spiral/docker-compose.yml
  .examples/symfony/composer.lock
  .examples/symfony/docker-compose.yml
  .examples/yii/composer.lock
  .examples/yii/docker-compose.yml
  docs/getting-started/index.rst
  integrations/laravel/composer.lock
  integrations/mezzio/composer.lock
  integrations/spiral/composer.lock
  integrations/symfony/composer.lock
  integrations/yii/composer.lock
  packages/seal-algolia-adapter/bin/drop_all_indexes.php
  packages/seal-algolia-adapter/composer.lock
  packages/seal-elasticsearch-adapter/composer.lock
  packages/seal-elasticsearch-adapter/docker-compose.yml
  packages/seal-loupe-adapter/composer.lock
  packages/seal-meilisearch-adapter/composer.lock
  packages/seal-memory-adapter/composer.lock
  packages/seal-multi-adapter/composer.lock
  packages/seal-opensearch-adapter/composer.lock
  packages/seal-read-write-adapter/composer.lock
  packages/seal-redisearch-adapter/composer.lock
  packages/seal-solr-adapter/composer.lock
  packages/seal-typesense-adapter/composer.lock
  packages/seal/composer.lock
Labels: Adapter: Elasticsearch, dependencies
