Repository PHP-CMSIG/search, pull requests merged in 2025-04, with the labels that each got.

#506 Add loupe context cropper library reference to documentation
  docs/search-and-filters/index.rst
Labels: documentation

#507 Fix getFieldByPath for Object and Typed Fields
  packages/seal/src/Schema/Index.php
  packages/seal/tests/Schema/IndexTest.php
Labels: bug

#508 Add mezcalito/ux-search to list about alternatives
  README.md
  docs/research/index.rst
Labels: documentation

#516 Add article about 'How Discord Indexes Trillions of Messages' to docs
  docs/research/index.rst
Labels: documentation

#518 Fix link in readme
  .examples/php-wasm-demo/.gitignore
  .examples/php-wasm-demo/composer.json
  .examples/php-wasm-demo/composer.lock
  .examples/php-wasm-demo/docker-bake.hcl
  .examples/php-wasm-demo/public/index.php
  README.md
Labels: documentation

#517 Upgrade elasticsearch docker images to 8.18.0
  .examples/laravel/docker-compose.yml
  .examples/mezzio/docker-compose.yml
  .examples/spiral/docker-compose.yml
  .examples/symfony/docker-compose.yml
  .examples/yii/docker-compose.yml
  docs/getting-started/index.rst
  packages/seal-elasticsearch-adapter/docker-compose.yml
Labels: Adapter: Elasticsearch, dependencies

#519 Update yii dependencies to latest versions
  .examples/php-wasm-demo/.gitignore
  .examples/php-wasm-demo/composer.json
  .examples/php-wasm-demo/composer.lock
  .examples/php-wasm-demo/docker-bake.hcl
  .examples/php-wasm-demo/public/index.php
  .examples/yii/composer.json
  .examples/yii/composer.lock
Labels: dependencies

#520 Add support for elasticsearch 9
  .examples/laravel/docker-compose.yml
  .examples/mezzio/docker-compose.yml
  .examples/spiral/docker-compose.yml
  .examples/symfony/docker-compose.yml
  .examples/yii/docker-compose.yml
  docs/getting-started/index.rst
  packages/seal-elasticsearch-adapter/composer.json
  packages/seal-elasticsearch-adapter/composer.lock
  packages/seal-elasticsearch-adapter/docker-compose.yml
Labels: features, Adapter: Elasticsearch, dependencies

#521 Update current composer dependencies
  .examples/laravel/composer.lock
  .examples/mezzio/composer.lock
  .examples/spiral/composer.lock
  .examples/symfony/composer.lock
  .examples/symfony/symfony.lock
  .examples/yii/composer.lock
  integrations/laravel/composer.lock
  integrations/mezzio/composer.lock
  integrations/spiral/composer.lock
  integrations/symfony/composer.lock
  integrations/yii/composer.lock
  packages/seal-algolia-adapter/composer.lock
  packages/seal-loupe-adapter/composer.lock
  packages/seal-meilisearch-adapter/composer.lock
  packages/seal-memory-adapter/composer.lock
  packages/seal-multi-adapter/composer.lock
  packages/seal-opensearch-adapter/composer.lock
  packages/seal-read-write-adapter/composer.lock
  packages/seal-redisearch-adapter/composer.lock
  packages/seal-solr-adapter/composer.lock
  packages/seal-typesense-adapter/composer.lock
  packages/seal/composer.lock
Labels: dependencies
